[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["NoahTheDuke"]
edition = "2018"

[dependencies]
arrayvec = "0.5.2"
itertools = "0.9.0"
lazy_static = "1.4.0"
lexical = "5.2.0"
regex = "1"
